### ISSUE TITLE
yo-list background-position 值的问题

### ISSUE THREAD

**Issue by dragonwong** [doyoe/Yo#12]
目前 `.yo-list > .item` 的 `background-position` 值一般为 `left <length> bottom`，这种“方向+距离”的写法在 微信安卓 webview （qq 浏览器 x5 内核）中失效。建议改为 `[ [ left | right ] | <length> ] [ [ top | bottom] | <length> ]` 这种写法。

比如：
```
background-position: left map-get($list, item-border-space) bottom;
```
修正为：
```
background-position: map-get($list, item-border-space) bottom;
```

**Comment by doyoe** [comment]
good job. TKS
