### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yuanxj1024** [doyoe/Yo#15]
mac os 下安装失败
AaronYuan@yuanxujiadeMacBook-Pro:~/Documents/Working/Practice/Yo⚡
⇒  npm install
npm WARN package.json yo@ No license field.
npm WARN deprecated gulp-sass@2.0.2: Empty partial bug copied to CSS folder fixed
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1

npm ERR! shasum check failed for /var/folders/x4/1f8vm8p550d67vd4lhdnpd180000gn/T/npm-18438-b1550815/registry.npmjs.org/node-notifier/-/node-notifier-4.2.3.tgz
npm ERR! Expected: 18ce4e6117980e23699b7595b68233cd37483fbf
npm ERR! Actual:   fb9cd807f7db221a16649f3f65dc028079fa538a
npm ERR! From:     https://registry.npmjs.org/node-notifier/-/node-notifier-4.2.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AaronYuan/Documents/Working/Practice/Yo/npm-debug.log

node,gulp,gem都是全局安装好的，所以直接在yo目录下执行npm install 结果报错了，求支援，谢谢

**Comment by doyoe** [comment]
调整了，你更新一下，重新install一次

**Comment by zhouwenbin** [comment]
@doyoe 现在安装只能用bower吗？bower很不稳定推荐用npm，和yeoman名字一样考虑换个名字也好推广，然后厂商前缀还有flexbox兼容可以考虑用autoprefixer
