### ISSUE TITLE
UI库特点

### ISSUE THREAD

**Issue by ouvens** [doyoe/Yo#22]
这里除了提供scss源码给开发者自己做，好像没其他的亮点啊，很多其它UI库也都有scss或less源码的

**Comment by doyoe** [comment]
Yo其实更多的是提供了很多能力，但自身并不做过多的预设。

比如包括：配置层的设计，元件同名方法的设计，超扩展的设计

我大概列一下它的一些特征：

Mobile First
iOS 风格（默认）
Pure CSS
分层设计
rem+px
封装了丰富的常规问题解决方案（形状，1px边框等）

**Comment by ouvens** [comment]
嗯，大概了解了，其实还是在功能上的集成更多的特点，像rem，响应式等。整体上设计思路还是也其它ui框架一样的。

**Comment by ouvens** [comment]
另外能加下你微信吗，你以前在去哪儿带过我一段时间的。我的1025224452，哈哈
