### ISSUE TITLE
关于多行省略

### ISSUE THREAD

**Issue by jackPanyj** [doyoe/Yo#23]
使用webkit的私有属性实现的会不会兼容性，不好。虽然caniuse上面写的支持度很好。但是我们项目经理还是不让用。他说有很多坑。让我们用字符串截取。不知道有没有很多坑？

**Comment by doyoe** [comment]
这么说吧。如果你的项目是移动端的，那么基本上问题不大，因为其实你很难找到iOS5.1和Android2.3之前的设备了，包括我们自己的项目，现在支持的基线也是iOS6.0+和Android4.0+
