### ISSUE TITLE
怎样用@include border 写一条边框？

### ISSUE THREAD

**Issue by MrKou47** [doyoe/Yo#26]
我看到border的参数并没有规定写那条边框，我要怎么实现使用border 只写div的上边框啊

**Comment by doyoe** [comment]
你可以这么做：

div {
    @include border(
        border-width: 1px 0 0,
        border-color: red
    );
}

类似这样就行，border方法提供的参数配置与原生border属性差不多，border-width, border-style, border-color 都可以传入

**Comment by doyoe** [comment]
另外：能问一下你是在哪家公司的产品上使用 Yo 呢，我可以加到用户列表，以后可以随时沟通 :)

**Comment by MrKou47** [comment]
哈哈，暂时还不能告诉你啊~
还有一个问题，我在用yo-checked的时候，input点击没有反应，我调整了一下input的z-index就可以了，不知道是不是我使用的姿势不正确啊..

**Comment by doyoe** [comment]
有可能啊，因为我不知道你的具体使用方式和场景，所以无法给出确定的答复
