### ISSUE TITLE
关于初学者的求助 : )

### ISSUE THREAD

**Issue by tandg1993** [doyoe/Yo#28]
之前有过基础的div+css+js/jquery+html5的开发过程，现在想跟你学习一下这个Yo框架，但是不知道何从下手

**Comment by doyoe** [comment]
嗯，Yo 其实很简单

首先你可以先 fork 一份代码到本地，然后按照 readme 里面的说明把 sass 的编译环境搭起来。

其次 Yo 主要是提供了各种能力和解决方案的集成，所以你可以快速的这样写代码：

比如你想让一个元素拥有 flex 布局

.test {
    @include flexbox;
}

**Comment by tandg1993** [comment]
好的，这么快收到回复真是有点受宠若惊呢~
