### ISSUE TITLE
综合实例

### ISSUE THREAD

**Issue by liangwind** [doyoe/Yo#32]
请问有没有yo+js使用的实例，方便新手入门使用，谢谢！

**Comment by doyoe** [comment]
因为之前有一个base yo的组件库，但是并没有开源，所以不太好讲。Yo即将推出的v3.0.0经过全新设计，将会涵盖一整套的组件，敬请期待

**Comment by doyoe** [comment]
@liangwind 请参阅 http://yo.doyoe.com/doc/ 文档，里面已经有了示例
