### ISSUE TITLE
$tip

### ISSUE THREAD

**Issue by chping2125** [doyoe/Yo#34]
初学yo，使用yo-tip时报下面的错误，没找到$zip变量，我也没发现在哪里，请教。
Message:
    src\styles\lib\widget\yo-tip.scss
Error: Undefined variable: "$tip".
        on line 9 of src/styles/lib/widget/yo-tip.scss
>>     padding: map-get($tip, padding);
   ---------------------^

**Comment by doyoe** [comment]
你用的是哪个版本？

**Comment by doyoe** [comment]
lib中的元件是不能被直接编译的，因为缺少依赖（事实上，也不会单独去编译它），我们要编译的通常都是一个page文件，这个page文件中至少包含有 usage/core/reset 文件和其它的元件。

请看 README.md 中的所说的“示例代码”

**Comment by chping2125** [comment]
您好，我用的是Yo-2.1.4版本
在使用tip元件之前，我也使用了其他元件，没有任何问题。
只有yo-tip这个元件有问题，根据报错（Error: Undefined variable: "$tip".）我去lib文件里找这个变量，也没有找到。
下面是我的工作路径，我在想是不是我gulp监听整个styles文件，然后css预处理导致的？
![工作路径图](http://chping.website/images/appTest.png)

前端初学，再次谢谢作者解答。

**Comment by doyoe** [comment]
lib/widget 下没有 yo-tip.scss 这个文件么？

**Comment by chping2125** [comment]
有呀。

**Comment by doyoe** [comment]
你动过 lib 这个目录下的文件吗？

**Comment by doyoe** [comment]
方便的话，你可以将工程发给我看看
