### ISSUE TITLE
为什么没有找到iconfont的文件呀？

### ISSUE THREAD

**Issue by nihaojob** [doyoe/Yo#38]

**Comment by doyoe** [comment]
对于 `Yo` 来讲，所有的资源都可以通过配置来使用，包括Iconfont。所以不论Iconfont文件在本地还是远端，都可以直接配置指向它的 `url`。

你可以在 varables.scss 文件里可以找到对 $_ico 路径的配置，如果你需要换一个Iconfont文件，只需要在 `config.scss` 文件里对它进行自定义：

```
$ico: (
    // {String} 图标字体文件名
    font-name:  yofont,
    // {Url} 图标字体路径
    font-path:  "//ss.qunarzz.com/yo/font/1.0.3/"
);
```

把 `font-path` 改成你的 Iconfont 地址即可，如果你的文件名叫 `aaa`，那么把 `font-name` 也相应的改成 `aaa`

**Comment by nihaojob** [comment]
非常感谢，已经解决了

**Comment by nihaojob** [comment]
非常感谢  解决了

**Comment by doyoe** [comment]
不客气
