### ISSUE TITLE
未找到的依赖项

### ISSUE THREAD

**Issue by luqin-Y** [doyoe/Yo#39]
"@qnpm/ykit-config-hy": "0.1.0",
    "@qnpm/ykit-config-qunar": "0.1.0",

**Comment by luqin-Y** [comment]
404 Not found : @qnpm/ykit-config-qunar

**Comment by Ellery0924** [comment]
hi，这两个依赖是yo开发时候的依赖，与使用无关，不过下个版本我们也会移除这两个依赖。如果要了解yo的使用方式，请参考文档站 http://yo.doyoe.com/doc/

**Comment by doyoe** [comment]
如 @Ellery0924 所说，这2个依赖是 `Yo` 自身开发时所使用到的依赖，和实际应用无关。因为实际应用是通过 `ykit init yo` 来构建标准 `Yo` 工程的，不需要直接 clone 源码。使用参考 http://yo.doyoe.com/doc/

**Comment by luqin-Y** [comment]
多谢

2017-01-11 16:56 GMT+08:00 杜瑶 <notifications@github.com>:
