### ISSUE TITLE
1px border 显示不完整

### ISSUE THREAD

**Issue by nihaojob** [doyoe/Yo#40]
自己在用yo框架的时候，经常出现1px不显示或者显示不完整的情况，有时候是因为margin元素影响，有时候是因为行内元素影响，自己不明白是因为什么问题导致的，想问一下使用1px边线时有什么需要规避的属性或者布局方式吗？ 谢谢了

**Comment by doyoe** [comment]
会出现这种情况，应该都是纵向的边框吧？

通常出现这种情况是因为，你应用了 border mixin 的元素可能宽度是通过 flex 自己计算出来的，这样的话它的宽度可能会是小数，而有些设备的渲染引擎对小数的精度渲染有问题，就导致了你所说的边框显示不完整的情况。

这通常只会在部分情况和机型上出现（你可以简单做个覆盖测试），如果想要解决这个问题的话，需要额外的单独处理一下，手工调整一下元素的宽度。

不过后续，我觉得厂商应该会解决这个问题

**Comment by nihaojob** [comment]
好的，知道了，非常感谢，以后我们再遇到这种问题的时候，就微调元素的宽高吧，非常感谢
