### ISSUE TITLE
Yo有@types文件吗？

### ISSUE THREAD

**Issue by MrKou47** [doyoe/Yo#43]
目前技术栈为react+typescript 不知yo是否有@types文件？
在我看来yo和antd很像都是基于react的组件库，只是antd是typescript写的..

希望yo也能抓紧推出@types文件

**Comment by doyoe** [comment]
Yo 暂时还没有这个计划，因为内部童鞋目前使用 ts 的不多，后续我们可能会考虑

**Comment by MrKou47** [comment]
好的，希望yo也走向ts的道路..之前开发一直用的yo2.x  现在技术栈换成ts+react了，只好另找ui库了

**Comment by Ellery0924** [comment]
虽然我不是很懂ts，但是通过npm安装的yo实际上都是编译后的es5代码，使用起来应该是没有问题的。
