### ISSUE TITLE
vue单文件组件里写@include报错啊

### ISSUE THREAD

**Issue by doKill** [doyoe/Yo#45]
`$ npm run dev

> vue-demo@1.0.0 dev D:\vue-demo
> node build/dev-server.js

> Starting dev server...
 ERROR  Failed to compile with 2 errors17:51:02

 error  in ./src/components/Login.vue

Module build failed:
        @include flexbox();
             ^
      No mixin named flexbox
`

**Comment by doyoe** [comment]
这个应该是你依赖没写正确，找不到 flexbox() 方法
